TERRAFORM_PLUGINS_DIRECTORY=/home/monta/.terraform.d/plugins

init:
	cd
	terraform init \
	-plugin-dir=${TERRAFORM_PLUGINS_DIRECTORY}

apply:
	terraform apply

plan:
	terraform plan

destroy:
	terraform destroy